= Parameters

The parent key for all of the following parameters is `openshift4_ingress`.


== `ingressControllers`

[horizontal]
type:: dictionary
default:: Default ingress controller.

A dictionary holding the `.spec` for ingress controllers.
The keys of the dict are used as names for the ingress controllers.

See the https://docs.openshift.com/container-platform/4.4/networking/ingress-operator.html#nw-ingress-controller-configuration-parameters_configuring-ingress[OpenShift docs] for available parameters.

The `domain` parameter is required.

To remove all ingress controllers, set to `null`.


== `ingressControllerAnnotations`

[horizontal]
type:: dictionary
default:: `{}`

A dictionary holding the `annotations` for ingress controllers.
The keys of the dict are the names of the ingress controllers to annotate.

== `cloud.provider`

[horizontal]
type:: string
default:: `${facts:cloud}`

The name of the cloud provider where the DNS service is hosted.
This usually should be the fact `cloud.provider`


== `cloud.credentials`

[horizontal]
type:: string
default:: undefined

The cloud provider credentials which will be used by the Issuer.
If this isn't set, a `CredentialsRequest` will be created.


== `cloud.gcp.projectName`

[horizontal]
type:: string
default:: undefined

The GCP project name in which the DNS setup is hosted.


== `cloud.aws.accessKey`

[horizontal]
type:: string
default:: undefined

Access key ID to be used for Route53 access.
The credentials will be created by this component via a `CredentialsRequest`.
Unfortunately the access key ID must be copied from the resulting secret:

[source,console]
--
kubectl get secret ingress-cert-issuer-credentials \
  -n openshift-ingress \
  -o jsonpath='{.data.aws_access_key_id}' | \
  base64 --decode
--


== `cloud.azure.clientID`

[horizontal]
type:: string
default:: undefined

[source,console]
--
kubectl get secret ingress-cert-issuer-credentials \
  -n openshift-ingress \
  -o jsonpath='{.data.azure_client_id}' | \
  base64 --decode
--


== `cloud.azure.subscriptionID`

[horizontal]
type:: string
default:: undefined

[source,console]
--
kubectl get secret ingress-cert-issuer-credentials \
  -n openshift-ingress \
  -o jsonpath='{.data.azure_subscription_id}' | \
  base64 --decode
--


== `cloud.azure.tenantID`

[horizontal]
type:: string
default:: undefined

[source,console]
--
kubectl get secret ingress-cert-issuer-credentials \
  -n openshift-ingress \
  -o jsonpath='{.data.azure_tenant_id}' | \
  base64 --decode
--


== `cloud.azure.resourceGroupName`

[horizontal]
type:: string
default:: undefined

[source,console]
--
kubectl get secret ingress-cert-issuer-credentials \
  -n openshift-ingress \
  -o jsonpath='{.data.azure_resourcegroup}' | \
  base64 --decode
--


== Example

[source,yaml]
----
parameters:
  openshift4_ingress:
    ingressControllers:
      prod:
        domain: apps.example.com
        defaultCertificate:
          name: prod-wildcard
        namespaceSelector:
          matchLabels:
            environment: prod
    ingressControllerAnnotations:
      prod:
        ingress.operator.openshift.io/default-enable-http2: true
----
